### ISSUE TITLE
Error: Unable to load celery application. The module planning was not found

### ISSUE THREAD

**Issue by easokol** [superdesk/superdesk-planning#1367]
I'm installing the plugin in superdesk server as described in readme:
add line
`git+git://github.com/superdesk/superdesk-planning.git@4ac564894eb2b89f6fdce82d0d1398ff5e2db47e#egg=superdesk-planning`
to requirements.txt inside server folder, then run
`pip install -r requirements.txt`
It shows
`Successfully installed deepdiff-3.3.0 icalendar-3.11.1 jsonpickle-1.2 python-dateutil-2.8.0 pytz-2019.3 setuptools-41.4.0 six-1.12.0 superdesk-planning-1.6.0`
Then I add line `'planning'` to `INSTALLED_APPS.extend([])` section of `settings.py`, then I restart the servicedesk service and I see in logs
```
Oct 23 18:37:39 ubuntu16 sh[6597]: 18:37:39 beat.1 | Error:
Oct 23 18:37:39 ubuntu16 sh[6597]: 18:37:39 beat.1 | Unable to load celery application.
Oct 23 18:37:39 ubuntu16 sh[6597]: 18:37:39 beat.1 | The module planning was not found.
Oct 23 18:37:39 ubuntu16 sh[6597]: 18:37:39 beat.1 |
Oct 23 18:37:39 ubuntu16 sh[6597]: 18:37:39 work.1 | Error:
Oct 23 18:37:39 ubuntu16 sh[6597]: 18:37:39 work.1 | Unable to load celery application.
Oct 23 18:37:39 ubuntu16 sh[6597]: 18:37:39 work.1 | The module planning was not found.
Oct 23 18:37:39 ubuntu16 sh[6597]: 18:37:39 work.1 |
Oct 23 18:37:39 ubuntu16 sh[6597]: 18:37:39 rest.1 | [2019-10-23 18:37:39 +0500] [6636] [ERROR] Exception in worker process
Oct 23 18:37:39 ubuntu16 sh[6597]: 18:37:39 rest.1 | Traceback (most recent call last):
Oct 23 18:37:39 ubuntu16 sh[6597]: 18:37:39 rest.1 |   File "/opt/superdesk/env/lib/python3.5/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
Oct 23 18:37:39 ubuntu16 sh[6597]: 18:37:39 rest.1 |     worker.init_process()
Oct 23 18:37:39 ubuntu16 sh[6597]: 18:37:39 rest.1 |   File "/opt/superdesk/env/lib/python3.5/site-packages/gunicorn/workers/base.py", line 129, in init_process
Oct 23 18:37:39 ubuntu16 sh[6597]: 18:37:39 rest.1 |     self.load_wsgi()
Oct 23 18:37:39 ubuntu16 sh[6597]: 18:37:39 rest.1 |   File "/opt/superdesk/env/lib/python3.5/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
Oct 23 18:37:39 ubuntu16 sh[6597]: 18:37:39 rest.1 |     self.wsgi = self.app.wsgi()
Oct 23 18:37:39 ubuntu16 sh[6597]: 18:37:39 rest.1 |   File "/opt/superdesk/env/lib/python3.5/site-packages/gunicorn/app/base.py", line 67, in wsgi
Oct 23 18:37:39 ubuntu16 sh[6597]: 18:37:39 rest.1 |     self.callable = self.load()
Oct 23 18:37:39 ubuntu16 sh[6597]: 18:37:39 rest.1 |   File "/opt/superdesk/env/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
Oct 23 18:37:39 ubuntu16 sh[6597]: 18:37:39 rest.1 |     return self.load_wsgiapp()
Oct 23 18:37:39 ubuntu16 sh[6597]: 18:37:39 rest.1 |   File "/opt/superdesk/env/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
Oct 23 18:37:39 ubuntu16 sh[6597]: 18:37:39 rest.1 |     return util.import_app(self.app_uri)
Oct 23 18:37:39 ubuntu16 sh[6597]: 18:37:39 rest.1 |   File "/opt/superdesk/env/lib/python3.5/site-packages/gunicorn/util.py", line 350, in import_app
Oct 23 18:37:39 ubuntu16 sh[6597]: 18:37:39 rest.1 |     __import__(module)
Oct 23 18:37:39 ubuntu16 sh[6597]: 18:37:39 rest.1 |   File "/opt/superdesk/server/wsgi.py", line 14, in <module>
Oct 23 18:37:39 ubuntu16 sh[6597]: 18:37:39 rest.1 |     application = get_app()
Oct 23 18:37:39 ubuntu16 sh[6597]: 18:37:39 rest.1 |   File "/opt/superdesk/server/app.py", line 41, in get_app
Oct 23 18:37:39 ubuntu16 sh[6597]: 18:37:39 rest.1 |     app = superdesk_app(config)
Oct 23 18:37:39 ubuntu16 sh[6597]: 18:37:39 rest.1 |   File "/opt/superdesk/env/lib/python3.5/site-packages/superdesk/factory/app.py", line 184, in get_app
Oct 23 18:37:39 ubuntu16 sh[6597]: 18:37:39 rest.1 |     install_app(module_name)
Oct 23 18:37:39 ubuntu16 sh[6597]: 18:37:39 rest.1 |   File "/opt/superdesk/env/lib/python3.5/site-packages/superdesk/factory/app.py", line 176, in install_app
Oct 23 18:37:39 ubuntu16 sh[6597]: 18:37:39 rest.1 |     app_module = importlib.import_module(module_name)
Oct 23 18:37:39 ubuntu16 sh[6597]: 18:37:39 rest.1 |   File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
Oct 23 18:37:39 ubuntu16 sh[6597]: 18:37:39 rest.1 |     return _bootstrap._gcd_import(name[level:], package, level)
Oct 23 18:37:39 ubuntu16 sh[6597]: 18:37:39 rest.1 | ImportError: No module named 'planning'

```

**Comment by romanianpaf** [comment]
Same here.
