### ISSUE TITLE
error when trying to install planner

### ISSUE THREAD

**Issue by trondhuso** [superdesk/superdesk-planning#1491]
this happens when I try and install the planning component/plugin

Collecting websockets<7.0,>=3.0
  Downloading websockets-5.0.1.tar.gz (68 kB)
     |████████████████████████████████| 68 kB 1.7 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-5rLV55/websockets/setup.py'"'"'; __file__='"'"'/tmp/pip-install-5rLV55/websockets/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-y2BPSO
         cwd: /tmp/pip-install-5rLV55/websockets/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-5rLV55/websockets/setup.py", line 1, in <module>
        import pathlib
    ImportError: No module named pathlib
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by trondhuso** [comment]
Last line says no module named pathlib so did this
pip install pathlib

then ran 
pip install -r requirements

then I got this:

ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-d_HyR5/websockets/setup.py'"'"'; __file__='"'"'/tmp/pip-install-d_HyR5/websockets/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-x0eari
         cwd: /tmp/pip-install-d_HyR5/websockets/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-d_HyR5/websockets/setup.py", line 24, in <module>
        raise Exception("websockets requires Python >= 3.4.")
    Exception: websockets requires Python >= 3.4.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

server runs 2.7 python.

is it safe to upgrade to 3.x?

**Comment by trondhuso** [comment]
Upgraded to python 3.6 using these commands:

sudo add-apt-repository ppa:deadsnakes/ppa
apt-get update

apt-get install python3.6
apt-get install python3.6-dev
apt-get install python3.7
apt-get install python3.7-dev
apt install python3-pip
update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.6 1
update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 1

pip3 install -r requirements.txt
